---
title: "UROPSummer2026"
format: html
editor: visual
---

## 

```{r}
setwd("/Users/haydenbosshardt/Desktop/SRI/RFiles/UROP/UROPSummer2026")
```

```{r}
library(tidyverse)
library(latex2exp)
library(readxl)
library(egg)
library(plotly)
library(readr)
library(neonUtilities) #download and manage NEON data (in-house)
library(neonOS) #NEON OS data
library(terra) #general geological data
library(ggplot2)
library(colorspace)
library(viridis)
library(sf)
library(tigris)
library(leaflet)
library(maps)
library(crosstalk)
```

## Test Run - April 2024 Only

```{r}
zipsByProduct(
  dpID = "DP4.00200.001",
  site = "ONAQ",
  startdate = "2024-04",
  enddate = "2024-04",
  package = "basic",
  check.size = FALSE
)
```

```{r}
setwd("/Users/haydenbosshardt/Desktop/SRI/RFiles/UROP")
getwd()

```

```{r}
AprilEddy <- stackEddy(
  filepath = "/Users/haydenbosshardt/Desktop/SRI/RFiles/UROP/UROPSummer2026/filesToStack00200/AprilSampleh5",
  level = "dp01",
  var = "tempAirTop",
  avg = 30
)

```

```{r}
write.csv(Eddy$ONAQ, file = "ONAQAprilAtm.csv")

```

```{r}
ONAQTRUEAprilAtm <- read_csv("/Users/haydenbosshardt/Desktop/SRI/RFiles/UROP/ONAQAprilAtm.csv")
```

## All

### Atm and Air Temp

```{r}
zipsByProduct(
  dpID = "DP4.00200.001",
  site = "ONAQ",
  startdate = "2022-01",
  enddate = "2024-12",
  package = "basic",
  check.size = FALSE
)
```

```{r}
AtmosEddy <- stackEddy(
  filepath = "/Users/haydenbosshardt/Desktop/SRI/RFiles/UROP/UROPSummer2026/ONAQAtmosH5",
  level = "dp01",
  var = "isoH2o",
  avg = 30
)

AirTempEddy <- stackEddy(
  filepath = "/Users/haydenbosshardt/Desktop/SRI/RFiles/UROP/UROPSummer2026/ONAQAtmosH5",
  level = "dp01",
  var = "tempAirTop",
  avg = 30
)
```

```{r}
write_csv(AtmosEddy$ONAQ, file = "ONAQAtmos.csv")
write_csv(AirTempEddy$ONAQ, file = "ONAQAirTemp.csv")
```

### Soil Water Iso

```{r}
zipsByProduct(
  dpID = "DP1.10086.001",
  site = "ONAQ",
  startdate = "2022-01",
  enddate = "2024-12",
  package = "basic",
  check.size = FALSE
  )
```

```{r}
SoilIsoEddy <- stackEddy(
  filepath = "/Users/haydenbosshardt/Desktop/SRI/RFiles/UROP/UROPSummer2026/filesToStack10086",
  level = "dp01",
  var = "soil",
  avg = 30
)
```

Need to add in csv file for this \*maybe

### Humidity

```{r}
ONAQhumidity <- loadByProduct(
  dpID = "DP1.00098.001",
  site = "ONAQ",
  startdate = "2022-01",
  enddate = "2024-12",
  package = "basic",
  check.size = FALSE
  
)

ONAQHumid <- as_tibble(ONAQhumidity$RH_30min)
write_csv(ONAQHumid, "ONAQRHumid.csv")
```

### Precipitation

```{r}
ONAQprecipitation <- loadByProduct(dpID = "DP1.00038.001", 
                                   site = "ONAQ",
                                   startdate = "2022-01",
                                   enddate = "2024-12",
                                   check.size = FALSE)

ONAQPrecip <- as_tibble(ONAQprecipitation$wdi_isoPerSample)

```

```{r}
write_csv(ONAQPrecip, "ONAQPrecip.csv")
```

# Start

### Atmosphere

```{r}
ONAQTRUEAtmos <- read_csv("/Users/haydenbosshardt/Desktop/SRI/RFiles/UROP/UROPSummer2026/ONAQAtmos.csv")
```

```{r}
ONAQAtmos <- ONAQTRUEAtmos %>% 
  rename(
    "d18Omean" = "data.isoH2o.dlta18OH2o.mean",
    "d2Hmean" = "data.isoH2o.dlta2HH2o.mean",
    "StartTime" = "timeBgn",
    "EndTime" = "timeEnd",
    "d18Omin" = "data.isoH2o.dlta18OH2o.min",
    "d18Omax" = "data.isoH2o.dlta18OH2o.max",
    "d2Hmin" = "data.isoH2o.dlta2HH2o.min",
    "d2Hmax" = "data.isoH2o.dlta2HH2o.max",
    "d18OSampleNumber" = "data.isoH2o.dlta18OH2o.numSamp",
    "d2HSampleNumber" = "data.isoH2o.dlta2HH2o.numSamp",
    "PressureMean" = "data.isoH2o.pres.mean",
    "PressureMin" = "data.isoH2o.pres.min",
    "PressureMax" = "data.isoH2o.pres.max",
    "PressureSampleNum" = "data.isoH2o.pres.numSamp",
    "TempMean" = "data.isoH2o.temp.mean",
    "TempMin" = "data.isoH2o.temp.min",
    "TempMax" = "data.isoH2o.temp.max",
    "DryMoleRatioMean" = "data.isoH2o.rtioMoleDryH2o.mean",
    "DryMoleRatioMin" = "data.isoH2o.rtioMoleDryH2o.min",
    "DryMoleRatioMax" = "data.isoH2o.rtioMoleDryH2o.max",
    "WetMoleRatioMean" = "data.isoH2o.rtioMoleWetH2o.mean",
    "WetMoleRatioMin" = "data.isoH2o.rtioMoleWetH2o.min",
    "WetMoleRatioMax" = "data.isoH2o.rtioMoleWetH2o.max"
    
  )
```

```{r}
#getting rid of unnecssary columns
ONAQAtmos <- ONAQAtmos %>% 
  select(horizontalPosition, verticalPosition, StartTime, EndTime, d18Omean, d18Omin, d18Omax, d18OSampleNumber, d2Hmean, d2Hmin, d2Hmax, d2HSampleNumber, PressureMean, PressureMin, PressureMax, PressureSampleNum, TempMean, TempMax, TempMin, DryMoleRatioMean, DryMoleRatioMin, DryMoleRatioMax, WetMoleRatioMean, WetMoleRatioMin, WetMoleRatioMax)

#adding row numbers
ONAQAtmos <- ONAQAtmos %>% 
  mutate(
    Row = row_number()
  )

#adding date of collection (20XX-XX)
ONAQAtmos <- ONAQAtmos %>%
  mutate(
    Date = format(StartTime, "%Y-%m")
  )

#getting rid of NA values
ONAQAtmos <- ONAQAtmos %>% 
  filter(d18OSampleNumber != 0)

ONAQAtmos <- ONAQAtmos %>% 
  filter(!is.na(d18Omean))
ONAQAtmos <- ONAQAtmos %>% 
  filter(!is.na(d2Hmean))
```

```{r}
#ONAQAtmos <- ONAQAtmos %>% 
  #mutate(
    #humidityratio = ((WetMoleRatioMean / DryMoleRatioMean) * 0.677)
  #)
```

### Checks

```{r}
#vertcheck <- ONAQAtmos %>% 
  #filter(verticalPosition == "h2oMed")

#vertcheck <- vertcheck %>% 
  #filter(!is.na(d18Omean))

```

### Precipitation

```{r}
ONAQTRUEPrecip <- read_csv("/Users/haydenbosshardt/Desktop/SRI/RFiles/UROP/UROPSummer2026/ONAQPrecip.csv")

```

```{r}
ONAQPrecip <- ONAQTRUEPrecip %>% 
  rename(
    "d18O" = "d18OWater",
    "d2H" = "d2HWater",
    "d18Osd" = "d18OsdWater",
    "d2Hsd" = "d2HsdWater",
    "d2Huncert" = "d2HWaterUncert",
    "d18Ouncert" = "d18OWaterUncert"
  )

#adding row numbers
ONAQPrecip <- ONAQPrecip %>% 
  mutate(
    Row = row_number()
  )

#adding date (20XX-XX)
ONAQPrecip <- ONAQPrecip %>%
  mutate(
    Date = format(collectDate, "%Y-%m")
  )
```

```{r}

ONAQPrecip <-  ONAQPrecip %>% 
  select(collectDate, d18O, d2H, d18Osd, d2Hsd, d18Ouncert, d2Huncert, Row, Date)
```

### Humidity

```{r}
ONAQTRUEHumid <- read_csv("/Users/haydenbosshardt/Desktop/SRI/RFiles/UROP/UROPSummer2026/ONAQRHumid.csv")
```

```{r}
ONAQHumid <- ONAQTRUEHumid %>% 
  rename(
    "StartTime" = "startDateTime",
    "EndTime" = "endDateTime",
    "RHMin" = "RHMinimum",
    "RHMax" = "RHMaximum",
    "MeanTempC" = "tempRHMean",
    "MinTempC" = "tempRHMinimum",
    "MaxTempC" = "tempRHMaximum",
    "dewTempMin" = "dewTempMinimum",
    "dewTempMax" = "dewTempMaximum"
  )


```

```{r}

#adding fahrenheit
ONAQHumid <- ONAQHumid %>% 
  mutate(
    Temp_F = MeanTempC * (9/5) + 32)

#adding kelvin
ONAQHumid <- ONAQHumid %>% 
  mutate(
    Temp_Kelvin = MeanTempC + 273.15)

```

```{r}
#adding row numbers
ONAQHumid <- ONAQHumid %>% 
  mutate(
    Row = row_number()
  )

#adding date (20XX-XX)
ONAQHumid <- ONAQHumid %>%
  mutate(
    Date = format(StartTime, "%Y-%m"))

#choosing wanted columns to keep in df
ONAQHumid <- ONAQHumid %>% 
  select(
    StartTime, EndTime, horizontalPosition, verticalPosition, RHMean, RHMin, RHMax, RHVariance, RHNumPts, RHExpUncert, RHStdErMean, MeanTempC, MinTempC, MaxTempC, tempRHVariance, tempRHNumPts, tempRHExpUncert, tempRHStdErMean, dewTempMean, dewTempMin, dewTempMax, Row, Date, Temp_F, Temp_Kelvin
  )
```

```{r}

#data frame for 40 ft tower measurment of humidity
ONAQHumid40 <- ONAQHumid %>% 
  filter(verticalPosition == "040")

#data frame for 0ft tower measurment of humidity
ONAQHumid0 <- ONAQHumid %>% 
  filter(verticalPosition == "000")
```

### Utah Lake Isotopes

```{r}
AllUtahCountyData <- read_csv("/Users/haydenbosshardt/Desktop/SRI/RFiles/UROP/UROPSummer2026/AllUtahCountyData.csv")
```

```{r}
#renaming some columns
AllUtahCountyData %>% rename(
  "Elevation" = "Elevation_mabsl"
)
```

```{r}
#creating df with no Tap samples
UtahLakeSamples <- AllUtahCountyData %>% 
  filter(!Type %in% c("Tap", "Milk", "Sprinkler"))

#creating lake only df
LakeOnlySamples <- AllUtahCountyData %>% 
  filter(Type == "Lake_or_pond")

#creating lake + river

RiverandLakeSamples <- AllUtahCountyData %>% 
  filter(Type == "Lake_or_pond" | Type == "River_or_stream")

#creating lake + river + spring

LakeRiverSpringSamples <- UtahLakeSamples %>% 
  filter(Type !="Ground")
```

```{r}
#box plot of samples by year
#all samples (except tap
#adding date (20XX-XX)
UtahLakeSamples <- UtahLakeSamples %>%
  mutate(
    Date = format(Collection_Date, "%Y-%m"))

UtahLakeSamples <- UtahLakeSamples %>% 
  mutate(
    Year = format(Collection_Date, "%Y")
  )

UtahLakeSamples <- UtahLakeSamples %>% 
  mutate(
    Row = row_number()
  )

#creating DONOTUSE row
UtahLakeSamples <- UtahLakeSamples %>% 
  mutate(
    DONOTUSE = FALSE
  )

#filtering out rows with DONOTUSE
UtahLakeSamples <- UtahLakeSamples %>% 
      mutate(DONOTUSE = Row %in% c( 3, 29, 38, 104, 105, 106, 108
          , TRUE, DONOTUSE))
```

```{r}
UtahLakeDF <- UtahLakeSamples %>%
  group_by(Date) %>% 
  summarise(across(where(is.numeric), mean,na.rm = TRUE))
```

#### Boxplots

```{r}
UtahLaked18Oplt <- UtahLakeSamples %>% 
  filter(DONOTUSE = FALSE) %>% 
  ggplot()+
  aes(x = Year, y = d18O)+
  geom_boxplot(
    fill = "lightblue", median.linewidth = 1.0, median.color = "lightblue4", box.color = "black", whisker.color = "black"
  )+
  theme_classic()

UtahLaked18Oplt
```

```{r}
#lake only samples
LakeOnlyd18Oplt <- UtahLakeSamples %>%
  filter(DONOTUSE == FALSE) %>% 
  filter(Type == "Lake_or_pond") %>% 
  ggplot()+
  aes(x = Year, y = d18O)+
  geom_boxplot(
    fill = "lightblue", median.linewidth = 1.0, median.color = "lightblue4", box.color = "black", whisker.color = "black"
  )+
  #scale_y_continuous(limits = c(-17, -2))+
  theme_classic()

LakeOnlyd18Oplt


#Lake and river only
LakeandRiverd18Oplt <- UtahLakeSamples %>%
  filter(DONOTUSE == FALSE) %>% 
  filter(Type == "Lake_or_pond" | Type == "River_or_stream") %>% 
  ggplot()+
  aes(x = Year, y = d18O)+
  geom_boxplot(
    fill = "lightblue", median.linewidth = 1.0, median.color = "lightblue4", box.color = "black", whisker.color = "black"
  )+
  #scale_y_continuous(limits = c(-17, -2))+
  theme_classic()

LakeandRiverd18Oplt


#Lake, River, Spring
LakeRiverSpringd18Oplt <- UtahLakeSamples %>%
  filter(DONOTUSE == FALSE) %>% 
  filter(Type == "Lake_or_pond" | Type == "River_or_stream" | Type == "Spring") %>% 
  ggplot()+
  aes(x = Year, y = d18O)+
  geom_boxplot(
    fill = "lightblue", median.linewidth = 1.0, median.color = "lightblue4", box.color = "black", whisker.color = "black"
  )+
  #scale_y_continuous(limits = c(-17, -2))+
  theme_classic()

LakeRiverSpringd18Oplt

LakeSpringd18Oplt <- UtahLakeSamples %>%
  filter(DONOTUSE == FALSE) %>% 
  filter(Type == "Lake_or_pond" | Type == "Spring") %>% 
  ggplot()+
  aes(x = Year, y = d18O)+
  geom_boxplot(
    fill = "lightblue", median.linewidth = 1.0, median.color = "lightblue4", box.color = "black", whisker.color = "black"
  )+
  #scale_y_continuous(limits = c(-17, -2))+
  theme_classic()

LakeSpringd18Oplt
```

```{r}
#lake only samples
LakeOnlyd2Hplt <- UtahLakeSamples %>%
  filter(DONOTUSE = FALSE) %>% 
  filter(Type == "Lake_or_pond") %>% 
  ggplot()+
  aes(x = Year, y = d2H)+
  geom_boxplot(
    fill = "indianred", median.linewidth = 1.0, median.color = "indianred4", box.color = "black", whisker.color = "black"
  )+
  theme_classic()

LakeOnlyd2Hplt


#Lake and river only
LakeandRiverd2Hplt <- UtahLakeSamples %>%
  filter(DONOTUSE = FALSE) %>% 
  filter(Type == "Lake_or_pond" | Type == "River_or_stream") %>% 
  ggplot()+
  aes(x = Year, y = d2H)+
  geom_boxplot(
    fill = "indianred", median.linewidth = 1.0, median.color = "indianred4", box.color = "black", whisker.color = "black"
  )+
  theme_classic()

LakeandRiverd2Hplt


#Lake, River, Spring
LakeRiverSpringd2Hplt <- UtahLakeSamples %>%
  filter(DONOTUSE = FALSE) %>% 
  filter(Type == "Lake_or_pond" | Type == "River_or_stream" | Type == "Spring") %>% 
  ggplot()+
  aes(x = Year, y = d2H)+
  geom_boxplot(
    fill = "indianred", median.linewidth = 1.0, median.color = "indianred4", box.color = "black", whisker.color = "black"
  )+
  theme_classic()

LakeRiverSpringd2Hplt

LakeSpringd2Hplt <- UtahLakeSamples %>%
  filter(DONOTUSE == FALSE) %>% 
  filter(Type == "Lake_or_pond" | Type == "Spring") %>% 
  ggplot()+
  aes(x = Year, y = d2H)+
  geom_boxplot(
    fill = "lightblue", median.linewidth = 1.0, median.color = "lightblue4", box.color = "black", whisker.color = "black"
  )+
  theme_classic()

LakeSpringd2Hplt
```

#### Map Plot

```{r}
UtahLakeSamples_Filtered <- UtahLakeSamples %>%
  filter(DONOTUSE == FALSE) 


UtahLakeSamples_sf <- st_as_sf(
  UtahLakeSamples_Filtered,
  coords = c("Longitude", "Latitude"),
             crs = 4326)
```

```{r}
pal <- colorFactor(
  palette = "Set1",
  domain = UtahLakeSamples$Year
)
```

```{r}
# Create shared data object
UtahLakeSharedSamples <- SharedData$new(UtahLakeSamples_sf)

# Create color palette by year
pal <- colorFactor(
  palette = "Set1",
  domain = UtahLakeSamples_sf$Year
)

# Interactive filtered map
bscols(
  widths = c(3, 9),
  
  filter_select(
    id = "Type",
    label = "Sample Type",
    sharedData = UtahLakeSharedSamples,
    group = ~Type
  ),
  
  leaflet(UtahLakeSharedSamples) %>%
    
    addProviderTiles(providers$Esri.WorldImagery) %>%
    
    addCircleMarkers(
      radius = 5,
      stroke = TRUE,
      weight = 1,
      fillOpacity = 0.8,
      
      color = ~pal(Year),
      fillColor = ~pal(Year),
      
      popup = ~paste(
        "Type:", Type,
        "<br>Year:", Year,
        "Row:", Row
      )
    ) %>%
    
    addLegend(
      position = "bottomright",
      pal = pal,
      values = ~Year,
      title = "Year"
    ) %>%
    
    setView(
      lng = -111.85,
      lat = 40.25,
      zoom = 10
    )
)
```

#### d2H v. d18O

```{r}
#all samples
Alld2Hvd18Oplt <- UtahLakeSamples %>% 
  ggplot()+
  aes(x= d18O, y = d2H, shape = Type, color = Year)+
  geom_point()+
  theme_minimal()

Alld2Hvd18Oplt

#lake samples only
Laked2Hvd18Oplt <- UtahLakeSamples %>% 
  filter(Type == "Lake_or_pond") %>% 
  ggplot()+
  aes(x= d18O, y = d2H, shape = Type, color = Year)+
  geom_point()+
  theme_minimal()

Laked2Hvd18Oplt

#lake and river samples

LakeandRiverd2Hvd18Oplt <- UtahLakeSamples %>% 
  filter(Type == "Lake_or_pond" | Type == "River_or_stream") %>% 
  ggplot()+
  aes(x= d18O, y = d2H, shape = Type, color = Year)+
  geom_point()+
  theme_minimal()

LakeandRiverd2Hvd18Oplt

#Lake, River, and Spring

LakeRiverSpringd2Hvd18Oplt <- UtahLakeSamples %>%
  filter(Type == "Lake_or_pond" | Type == "River_or_stream" | Type == "Spring") %>% 
  ggplot()+
  aes(x= d18O, y = d2H, shape = Type, color = Year)+
  geom_point()+
  theme_minimal()

LakeRiverSpringd2Hvd18Oplt
```

### Matos et al. Graphs

### Analysis

#### Precipitation (amount weighted)

$$\delta_w = \frac{\sum_{i=1}^{n} P_i \delta_i}{\sum_{i=1}^{n} P_i}$$

------------------------------------------------------------------------

##### SKIPPPPP

```{r}
ONAQprecipitationamount <- loadByProduct(
  dpID = "DP1.00044.001",
  site = "ONAQ",
  startdate = "2022-01",
  enddate = "2024-12",
  package = "basic",
  check.size = FALSE
)
```

```{r}
ONAQPrecipAmountDaily <- as_tibble(ONAQprecipitationamount$WEIPRE_daily)

ONAQPrecipAmount60 <- as_tibble(ONAQprecipitationamount$WEIPRE_60min)
```

```{r}
write_csv(ONAQPrecipAmount60, "ONAQPrecipAmount60.csv")

write_csv(ONAQPrecipAmountDaily, "ONAQPrecipAmountDaily.csv")
```

------------------------------------------------------------------------

##### START!

```{r}
ONAQPrecipAmount60 <- read_csv("/Users/haydenbosshardt/Desktop/SRI/RFiles/UROP/UROPSummer2026/ONAQPrecipAmount60.csv")

ONAQPrecipAmountDaily <- read_csv("/Users/haydenbosshardt/Desktop/SRI/RFiles/UROP/UROPSummer2026/ONAQPrecipAmountDaily.csv")
```

```{r}
#in daily precip measurments df - get rid of any days that have 0 precipitation
ONAQPrecipAmountCompare <- ONAQPrecipAmountDaily %>% 
  filter(precipBulk != 0)
```

```{r}
ONAQPrecipAmountCompare <- ONAQPrecipAmountCompare %>% 
  rename(
    "CollectionDate" = "date"
  )
```

```{r}
#Adding Date
ONAQPrecipAmountCompare <- ONAQPrecipAmountCompare %>% 
  mutate(
    Date = format(CollectionDate, "%Y-%m")
  )


```

```{r}
#calculating average precipitation amounts per month
ONAQPrecipAmountCompareAvg <- ONAQPrecipAmountCompare %>%
  group_by(Date) %>% 
  summarise(PrecipAmountAvg = mean(precipBulk, na.rm = TRUE))

#adding back in 2024-06
ONAQPrecipAmountCompareAvg %>%  add_row(Date = "2024-06", PrecipAmountAvg = 0)

```

##### Sample Plot:

```{r}
ViewPrecipAmountplt <- ONAQPrecipAmountCompareAvg %>% 
  ggplot()+
  aes(x = Date, y = PrecipAmountAvg)+
  geom_point()+
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 45))

ViewPrecipAmountplt

ViewPrecipAmount2022plt <- ONAQPrecipAmountCompareAvg %>%
  filter(substr(Date, 1, 4) == "2022") %>% 
  ggplot()+
  aes(x = Date, y = PrecipAmountAvg)+
  geom_point()+
  theme_minimal()
  
ViewPrecipAmount2022plt


```

```{r}
#average each month of precipitation isotopes for d18O and d2H
ONAQPrecipMonthAvg <- ONAQPrecip %>%
  group_by(Date) %>% 
  summarise(PrecipAvgd18Omean = mean(d18O, na.rm = TRUE),
            PrecipAvgd2Hmean = mean(d2H, na.rm = TRUE))
```

```{r}
#adding in missing months to precip isotope values
ONAQPrecipMonthAvg %>% add_row(Date = "2022-02", PrecipAvgd18Omean = 0, PrecipAvgd2Hmean = 0)
ONAQPrecipMonthAvg %>% add_row(Date = "2024-06", PrecipAvgd18Omean = 0, PrecipAvgd2Hmean = 0)

#combining precip amounts and precip isotopes into the same df (d18O)
ONAQPrecipAmountd18OCombinedMonthAvg <-
  bind_cols(ONAQPrecipAmountCompareAvg %>% select(Date, PrecipAmountAvg), ONAQPrecipMonthAvg %>% select(PrecipAvgd18Omean)
  )

#combining precip amounts and precip isotopes into the same df (d2H)
ONAQPrecipAmountd2HCombinedMonthAvg <-
  bind_cols(ONAQPrecipAmountCompareAvg %>% select(Date, PrecipAmountAvg), ONAQPrecipMonthAvg %>% select(PrecipAvgd2Hmean)
  )
```

```{r}
#calculating amount weighted isotopes for d18O
ONAQPrecipWeightedd18O <- ONAQPrecipAmountCombinedMonthAvg %>%
  group_by(Date) %>%
  summarise(
    d18OWeighted =
      sum(PrecipAmountAvg * PrecipAvgd18Omean, na.rm = TRUE) /
      sum(PrecipAmountAvg, na.rm = TRUE)
  )

#calculating amount weighted isotopes for d2H
ONAQPrecipWeightedd2H<- ONAQPrecipAmountCombinedMonthAvg %>%
  group_by(Date) %>%
  summarise(
    d2HWeighted =
      sum(PrecipAmountAvg * PrecipAvgd18Omean, na.rm = TRUE) /
      sum(PrecipAmountAvg, na.rm = TRUE)
  )
```

#### Fractionation Factor

\$\$

\$\$

$$\alpha = \frac{R_l}{R_v}$$

```{r}
#Monthly averages
ONAQAtmosMonthAvg <- ONAQAtmos %>%
  group_by(Month) %>%  
  summarise(AtmosAvgd18Omean = mean(d18Omean, na.rm = TRUE),
            AtmosAvgd2Hmean = mean(d2Hmean, na.rm = TRUE))


ONAQPrecipMonthAvg <- ONAQPrecip %>%
  group_by(Month) %>% 
  summarise(PrecipAvgd18Omean = mean(d18O, na.rm = TRUE),
            PrecipAvgd2Hmean = mean(d2H, na.rm = TRUE))

```

```{r}
ONAQd18OCombinedMonthAvg <- 
  bind_cols(ONAQPrecipMonthAvg %>% select(Month, PrecipAvgd18Omean), ONAQAtmosMonthAvg %>% select(AtmosAvgd18Omean)
  )

ONAQd2HCombinedMonthAvg <- 
  bind_cols(ONAQPrecipMonthAvg %>% select(Month, PrecipAvgd2Hmean), ONAQAtmosMonthAvg %>% select(AtmosAvgd2Hmean)
  )
```

```{r}
ONAQd18OCombinedMonthAvg <- 
  bind_cols(Weightedd18O %>% select(Month, Weightedd18O), ONAQAtmosMonthAvg %>% select(AtmosAvgd18Omean)
  )

```

```{r}
ONAQd18OCombinedMonthAvg <- ONAQd18OCombinedMonthAvg %>% 
  mutate(
    FractionationFactor = (Weightedd18O/AtmosAvgd18Omean))

ONAQd2HCombinedMonthAvg <- ONAQd2HCombinedMonthAvg %>% 
  mutate(
    FractionationFactor = (PrecipAvgd2Hmean/AtmosAvgd2Hmean))
  
```

### Plots

```{r}
ONAQAtmplt1 <- ONAQAtmos %>% 
  ggplot()+
  aes(x = Year, y = d18Omean)+
  geom_boxplot(fill = "lightblue", median.linewidth = 1.0, median.color = "lightblue4", box.color = "black", whisker.color = "black"
  )+
  theme_classic()

ONAQAtmplt1
```

```{r}
ONAQAtmplt2 <- ONAQAtmos %>% 
  ggplot()+
  aes(x = d18Omean, y = d2Hmean)+
  geom_point()+
  geom_abline(slope = 7, intercept = 0, color = "#6FA458", linewidth = 1) +
  geom_abline(slope = 7.45, intercept = -1.65, color = "#5B2C4D", linetype = 3, size = 2)+
  theme_classic()

ONAQAtmplt2
```

```{r}
ONAQAtm2022 <- ONAQAtmos %>% 
  filter(Year == 2022)  


ONAQAtmHumidity2022 <- ONAQAtm2022 %>% 
  ggplot()+
  aes(x = StartTime,  y = humidityratio)+
  geom_point()+
  theme_classic()

ONAQAtmHumidity2022
```

```{r}
ONAQd18OCombinedMonthAvgPlt <- ONAQd18OCombinedMonthAvg %>% 
  ggplot()+
  geom_point(aes(x = Month, y = AtmosAvgd18Omean))+
  geom_point(aes(x = Month, y = PrecipAvgd18Omean))+
  theme_classic()

ONAQd18OCombinedMonthAvgPlt
```
